version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: greenfy_app
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - greenfy_net

  db:
    image: postgres:15
    container_name: greenfy_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-greenfy_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - greenfy_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: greenfy_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5058:80"
    depends_on:
      - db
    networks:
      - greenfy_net

volumes:
  pgdata:
  pgadmin_data:

networks:
  greenfy_net:
    driver: bridge